### ISSUE TITLE
ImportError: No module named 'django.utils.importlib'

### ISSUE THREAD

**Issue by korolr** [frankban/django-endless-pagination#96]
Django 1.9.7 compatibility issue in following files:
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x108d071e0>
Traceback (most recent call last):
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(_args, *_kwargs)
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(__exception)
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(_args, **kwargs)
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/django/**init**.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/admin/Desktop/django/da/lib/python3.5/importlib/**init**.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/endless_pagination/models.py", line 11, in <module>
    from endless_pagination import (
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/endless_pagination/loaders.py", line 6, in <module>
    from django.utils.importlib import import_module
ImportError: No module named 'django.utils.importlib'

**Comment by holayeah** [comment]
Same issue, django = 1.9.7

**Comment by modiparth95** [comment]
Can anyone guide me how to solve this error i am getting same error in django = 1.10.8 ?
